//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonDomain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonDomain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.Domain.CommonDomain", typeof(CommonDomain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action type.
        /// </summary>
        public static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval requests.
        /// </summary>
        public static string ApprovalRequests {
            get {
                return ResourceManager.GetString("ApprovalRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved at.
        /// </summary>
        public static string ApprovedAt {
            get {
                return ResourceManager.GetString("ApprovedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current stocks.
        /// </summary>
        public static string CurrentStocks {
            get {
                return ResourceManager.GetString("CurrentStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended at.
        /// </summary>
        public static string EndedAt {
            get {
                return ResourceManager.GetString("EndedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From inventory.
        /// </summary>
        public static string FromInventory {
            get {
                return ResourceManager.GetString("FromInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From stock movement.
        /// </summary>
        public static string FromStockMovement {
            get {
                return ResourceManager.GetString("FromStockMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From stock movements.
        /// </summary>
        public static string FromStockMovements {
            get {
                return ResourceManager.GetString("FromStockMovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From storage room.
        /// </summary>
        public static string FromStorageRoom {
            get {
                return ResourceManager.GetString("FromStorageRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventories.
        /// </summary>
        public static string Inventories {
            get {
                return ResourceManager.GetString("Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product category.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product in storage room.
        /// </summary>
        public static string ProductInStorageRoom {
            get {
                return ResourceManager.GetString("ProductInStorageRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product in storage rooms.
        /// </summary>
        public static string ProductInStorageRooms {
            get {
                return ResourceManager.GetString("ProductInStorageRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role claim.
        /// </summary>
        public static string RoleClaim {
            get {
                return ResourceManager.GetString("RoleClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock audit.
        /// </summary>
        public static string StockAudit {
            get {
                return ResourceManager.GetString("StockAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock audits.
        /// </summary>
        public static string StockAudits {
            get {
                return ResourceManager.GetString("StockAudits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock movement.
        /// </summary>
        public static string StockMovement {
            get {
                return ResourceManager.GetString("StockMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage room.
        /// </summary>
        public static string StorageRoom {
            get {
                return ResourceManager.GetString("StorageRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage room in inventories.
        /// </summary>
        public static string StorageRoomInInventories {
            get {
                return ResourceManager.GetString("StorageRoomInInventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage room in inventory.
        /// </summary>
        public static string StorageRoomInInventory {
            get {
                return ResourceManager.GetString("StorageRoomInInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To inventory.
        /// </summary>
        public static string ToInventory {
            get {
                return ResourceManager.GetString("ToInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To stock movement.
        /// </summary>
        public static string ToStockMovement {
            get {
                return ResourceManager.GetString("ToStockMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To stock movements.
        /// </summary>
        public static string ToStockMovements {
            get {
                return ResourceManager.GetString("ToStockMovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To storage room.
        /// </summary>
        public static string ToStorageRoom {
            get {
                return ResourceManager.GetString("ToStorageRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User claim.
        /// </summary>
        public static string UserClaim {
            get {
                return ResourceManager.GetString("UserClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User token.
        /// </summary>
        public static string UserToken {
            get {
                return ResourceManager.GetString("UserToken", resourceCulture);
            }
        }
    }
}
